# Mostly implied or set by GitHub after push.
safe: true
source: .
destination: ./_site
lsi: false
pygments: true

# Metadata used by jekyll (baseurl appears to do nothing but it is documented.)
exclude: CNAME, Makefile
permalink: ":year/:month/:title.exe"
baseurl: //sporkexec.com/
#baseurl: file:///home/jake/dev/sporkexec.github.com/_site/

# Used by the site.
title: sporkexec.com
author_name: Jacob Courtneay
author_contact: jacob@sporkexec.com
repo_url: https://github.com/sporkexec/sporkexec.github.com
